---
db:
  image: postgres
testoutput:
  image: busybox
  volumes:
    - /test-output
app:
  image: dordoka/play-framework
  links:
   - db
  volumes:
   - ./nationbuilder-app:/home/play/Code
   - ~/.ivy2:/home/play/Code/.ivy2
   - ~/.sbt:/home/play/Code/.sbt
  volumes_from:
   - testoutput
  ports:
   - "9000:9000"
   - "9999:9999"
   - "8888:8888"
  environment:
    DEBUG: True
    DATABASE_URL: "postgres://postgres@db/postgres"
